---
- name: Configure macOS
  hosts: all
  become: true
  vars:
    logrotate_scripts:
      - name: "Configure logrotate with the log file"
        path: "{{ log_path }}/{{ log_file_name }}"
        options:
          - daily
          - missingok
          - rotate 7
          - maxage 7
          - dateext
          - dateyesterday

  roles:
    - l50.ansible_spacevim


